version: '3.8'

services:
  # Servicio de la aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis
      - meilisearch

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: laraveluser
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  # Meilisearch
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: masterKey1234567890
      MEILI_ENV: production
    volumes:
      - meilisearch_data:/data.ms
    ports:
      - "7700:7700"
    networks:
      - laravel-network

  # Horizon (opcional, para queues)
  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_horizon
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - redis
      - mysql
    command: php artisan horizon

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  meilisearch_data:
    driver: local

networks:
  laravel-network:
    driver: bridge