version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app:latest
    container_name: laravel_app
    depends_on:
      - mysql
      - redis
      - meilisearch
    volumes:
      - .:/var/www/html:delegated
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/overrides.ini:ro
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: products_laravel
      DB_USERNAME: products_laravel
      DB_PASSWORD: admin
      REDIS_HOST: redis
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: masterKey
    networks:
      - laravel

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_laravel
      MYSQL_USER: products_laravel
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

  meilisearch:
    image: getmeili/meilisearch:v1.12.0
    container_name: laravel_meilisearch
    environment:
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meili_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - laravel

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_worker
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/var/www/html:delegated
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    networks:
      - laravel

volumes:
  mysql_data:
  redis_data:
  meili_data:

networks:
  laravel:
    driver: bridge
